### ISSUE TITLE
The dependency is not working for Nestjs 8.0.5

### ISSUE THREAD

**Issue by Jedliu** [SuperAwesomeLTD/permissions-nestjs#12]
Hi,

The installation failed. Please check. Thank you!

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-nestjs-starter@0.0.1
npm ERR! Found: @nestjs/common@8.0.5
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^8.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^6.0.0" from @superawesome/permissions-nestjs@1.0.1
npm ERR! node_modules/@superawesome/permissions-nestjs
npm ERR!   @superawesome/permissions-nestjs@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by Jedliu** [comment]
I tried to copy the code of permissions-nestjs to my project (Nestjs v8.0.0) but it failed with the below errors.

```
(node:53482) UnhandledPromiseRejectionWarning: Error: SA-Permissions: cant build with empty permissionDefinitions!
    at Object.exports.buildAccessControl (/Users/user_name/Code/nestjs-starter/node_modules/@superawesome/permissions/src/utils.ts:81:11)
    at Permissions.build (/Users/user_name/Code/nestjs-starter/node_modules/@superawesome/permissions/src/Permissions.ts:197:41)
    at PermissionsService.onModuleInit (/Users/user_name/Code/nestjs-starter/src/permissions/permissions.service.ts:14:22)
    at MapIterator.iteratee (/Users/user_name/Code/nestjs-starter/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)
    at MapIterator.next (/Users/user_name/Code/nestjs-starter/node_modules/iterare/src/map.ts:9:39)
    at IteratorWithOperators.next (/Users/user_name/Code/nestjs-starter/node_modules/iterare/src/iterate.ts:19:28)
    at Function.from (<anonymous>)
    at IteratorWithOperators.toArray (/Users/user_name/Code/nestjs-starter/node_modules/iterare/src/iterate.ts:227:22)
    at callOperator (/Users/user_name/Code/nestjs-starter/node_modules/@nestjs/core/hooks/on-module-init.hook.js:23:10)
    at Object.callModuleInitHook (/Users/user_name/Code/nestjs-starter/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:23)
```

**Comment by Jedliu** [comment]
I found the solution. Should update [GetPermit.decorator.ts](https://github.com/SuperAwesomeLTD/permissions-nestjs/blob/master/src/GetPermit.decorator.ts) to
```
export const GetPermit = createParamDecorator((data, ctx): Permit => {
  const req = ctx.switchToHttp().getRequest();

  if (!req.__permissions_permit__)
```
